development:
  adapter: mysql2
  database: checkn_development
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: checkn_test
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: my_6661
  pool: 5
  timeout: 5000
  encoding: utf8
  username: my_6661a
  password: qweasdzxc
  host: bluecheckpoint.megiteam.pl:3307
